### ISSUE TITLE
TODO: Pokój 432

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/GraTerenowa#13]
porównanie kątów i wielkości

**Comment by MarcinKosinski** [comment]
Tego pokoju nie ma w `README.md`

**Comment by pbiecek** [comment]
będzie za godzinę, jeszcze nie jest przygotowany

**Comment by pbiecek** [comment]
dodane w pliku mini8888.html

**Comment by MarcinKosinski** [comment]
Świetne!

**Comment by MarcinKosinski** [comment]
Brakuje mi tylko czasem jakiegoś bardziej kolorowego szablonu, upiększaczy, loga Bety i Bita, rysunków :) ale to już nie jest mus

**Comment by pbiecek** [comment]
Takie upiększacze musiałby zrobić ktoś o odpowiedniej wrażliwości
estetycznej (czyli nie ja ;-)).
Zróbmy w czerwcu gry, opowiadania, komiksy i za zakończeniu czerwcowej
kampanii poszukam funduszy na dalsze prace (już bardizej dopracowane
graficznie)

2016-05-25 11:53 GMT+02:00 Marcin Kosiński notifications@github.com:

> Brakuje mi tylko czasem jakiegoś bardziej kolorowego szablonu,
> upiększaczy, loga Bety i Bita, rysunków :) ale to już nie jest mus
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/13#issuecomment-221526746

## 

pozdrawiam serdecznie,
Przemysław Biecek
