### ISSUE TITLE
Lista pokoi

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#14]
@pbiecek  Jakie numery pokoi są dostępne, gdyby chcieć dodawać nowe wykresy? W sensie, które są wolne i do wykorzystania?

**Comment by pbiecek** [comment]
Teraz jest 10 zagadek, 
każda zagadka jest opisana przez cztery cyfry (to nazwy klików na githubie i nazwy kodów QR)
pokoje są przypisywane elastycznie do tych czterocyfrowych kodów,
idę korytarzem, jak widzę fajną przestrzeń to naklejam !R kod,
na kodzie nie ma informacji o pokoju, tylko o tym 4 cyfrowym kodzie.
Lokalizacja który kod przy którym pokoju jest trzymana na serwerze.

Tak więc wykorzystać możesz wszystkie wolne czterocyfrowe kody - poza tymi, które są już na githubie.

**Comment by pbiecek** [comment]
Zapomniałem dodać, aplikacja nie ma zaszytych na sztywno ani kodów ani numerów pokoji, 
wszystko dostaje jako json z serwera

**Comment by pbiecek** [comment]
I jeszcze @MarcinKosinski dla notyfikacji

**Comment by MarcinKosinski** [comment]
Ok dzięki za informacje. Jak zakładam wątek, to już `@` nie jest potrzebna. Tak samo, gdy sie juz raz udzielę w wątku.

**Comment by pbiecek** [comment]
Czy przygotowujesz teraz zadania?
Jeżeli tak to ile i na kiedy?
W połowie czerwca mamy też grę na mimuwie, więc nowe zadania by się
przydały.

2016-05-24 19:41 GMT+02:00 Marcin Kosiński notifications@github.com:

> Ok dzięki za informacje. Jak zakładam wątek, to już @ nie jest potrzebna.
> Tak samo, gdy sie juz raz udzielę w wątku.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/14#issuecomment-221344620

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Wrzucę kilka propozycji `%in% c('dziś wieczorem','dziś w nocy','jutro rano')`, zobaczę ile uda się wyczarować :) Możesz je dorzucić do MiNI, możesz je dorzucić do MIMUW. Jak Ci pasuje.

**Comment by MarcinKosinski** [comment]
`kilka <- sample(10:30, size = 1)`

**Comment by MarcinKosinski** [comment]
Używam takich numerów pokoi: 1000-1030

zastanawialem sie czy mowi sie `pokoi` czy `pokojow` ale sie nie dowiedzialame :P
http://sjp.pwn.pl/poradnia/haslo/pokojow-czy-pokoi;10381.html

**Comment by pbiecek** [comment]
Super
