### ISSUE TITLE
Pokój X01 - DT::datatable PogromcyDanych::auta2012

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#15]
Nazwę wątku można wyedytować, gdy namyślisz się jaki mógłby być ostateczny numer pokoju.

Odpowiedź do tej zagadki to `28000` . Co o tym sądzisz?

**Comment by MarcinKosinski** [comment]
![pokoj_x01](https://cloud.githubusercontent.com/assets/6773454/15514851/6ab89228-21eb-11e6-96f9-bb8352d8abac.png)

**Comment by MarcinKosinski** [comment]
Kiedyś @krzyslom tłumaczył mi jak ustawić opcje `DT:datatable`,  żeby pokazywało polskie napisy (zamiast `Show 5 entries` to `Pokaż 5 obserwacji`). @krzyslom , czy to ostatecznie działało? Wiesz może jak pozbyć się numerów wierszy w `DT:datatable`

**Comment by MarcinKosinski** [comment]
@pbiecek  zapomniałem w pierwszej wiadomości

**Comment by pbiecek** [comment]
Spójrz proszę na format poprawionych zadań, np tutaj: https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini0998.html
https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini0999.html
https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1313.html

(na telefonie wygląda inaczej),

format zmienił się zgodnie z Twoimi sugestiami, 
nie ma numeru pokoju, pierwsze zdanie to Zadanie:
Poźniej max jedno zdanie.
Później wykres/tabela
i pod wykresem tabelą jest ewentualnie wiecej ciekawostek, wskazówek, inforamacji

**Comment by pbiecek** [comment]
Zadanie fajne, trzeba by tylko sprawdzić czy ta tabela zmieści sie na ekranie telefonu

**Comment by MarcinKosinski** [comment]
Poprawka 
https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1000.html

**Comment by MarcinKosinski** [comment]
Usunalem nazwy wierszy.

**Comment by MarcinKosinski** [comment]
@krzyslom obiecal zglosic PR z polskim jezykiem w tabeli :)

**Comment by MarcinKosinski** [comment]
@pbiecek na komorce wyglada calkiem znosnie :) dodajemy do aplikacji?

**Comment by pbiecek** [comment]
Ok, wyjdzie w praniu

2016-05-29 22:00 GMT+02:00 Marcin Kosiński notifications@github.com:

> @pbiecek https://github.com/pbiecek na komorce wyglada calkiem znosnie
> :) dodajemy do aplikacji?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/15#issuecomment-222379627,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvi8do6NkP3xOkEaYtO7FaIVi7BHiks5qGfBUgaJpZM4IlxQi
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Zamykac issue, czy zrobisz to Ty kiedy cost tam wgrasz do aplikacji?

**Comment by pbiecek** [comment]
Ok, to może ja zamknę issue dodając zadanie do apki.

Wygeneruj jeszcze proszę kod QR dla tego zadania.
Instrukcję jak generować te kody umieściłem tutaj:
https://github.com/BetaAndBit/GraTerenowa/wiki/Jak-dodawa%C4%87-zadania

2016-05-29 22:31 GMT+02:00 Marcin Kosiński notifications@github.com:

> Zamykac issue, czy zrobisz to Ty kiedy cost tam wgrasz do aplikacji?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/15#issuecomment-222381094,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvraMvBQYFV3O2CXZ5JGcX-f16j7sks5qGfeogaJpZM4IlxQi
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
w mini1000 - Biblioteka wprowadzilem ostatnie poprawki lingwistyczne. Mozna zaktualizowac zagadke na serwerze.
