### ISSUE TITLE
Pokój X02 - mapa świata, stolice

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#16]
Nie każdy pomysł jest najlepszy, ale może na wersję tabletową :) ?

**Comment by MarcinKosinski** [comment]
![pokoj_x02](https://cloud.githubusercontent.com/assets/6773454/15517910/9abffe34-21fa-11e6-9ec8-a46229bdff49.png)

@pbiecek

**Comment by pbiecek** [comment]
Na telefonie komórkowym może być to trudno odczytać.
Może gdyby tę mapę przyciąć tylko do afryki?

2016-05-24 22:43 GMT+02:00 Marcin Kosiński notifications@github.com:

> [image: pokoj_x02]
> https://cloud.githubusercontent.com/assets/6773454/15517910/9abffe34-21fa-11e6-9ec8-a46229bdff49.png
> 
> @pbiecek https://github.com/pbiecek
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/16#issuecomment-221384304

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Jest to zawsze jakies rozwiazanie :)

**Comment by MarcinKosinski** [comment]
Póki co https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1001.html

**Comment by pbiecek** [comment]
Zadanie fajne, ale raczej nie na komórkę.
U mnie ten wykres zajmuje 3 szerokości ekranu i nie mogę go pomniejszyć
Może te dane pokazać jakoś inaczej ? w węższy sposób?

2016-05-25 15:37 GMT+02:00 Marcin Kosiński notifications@github.com:

> Póki co
> https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1001.html
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/16#issuecomment-221578416

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Pracuję nad przycięciem do Afryki, ewentualnie można to zrobić dla Europy.

W dniu 25 maja 2016 18:22 użytkownik Przemysław Biecek <
notifications@github.com> napisał:

**Comment by pbiecek** [comment]
Dla Europy to dobry pomysł (o ile da się przyciąć mapę)

W dniu 25 maja 2016 18:39 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Pracuję nad przycięciem do Afryki, ewentualnie można to zrobić dla Europy.
> 
> W dniu 25 maja 2016 18:22 użytkownik Przemysław Biecek <
> notifications@github.com> napisał:
> 
> > Zadanie fajne, ale raczej nie na komórkę.
> > U mnie ten wykres zajmuje 3 szerokości ekranu i nie mogę go pomniejszyć
> > Może te dane pokazać jakoś inaczej ? w węższy sposób?
> > 
> > 2016-05-25 15:37 GMT+02:00 Marcin Kosiński notifications@github.com:
> > 
> > > Póki co
> > > https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1001.html
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/BetaAndBit/GraTerenowa/issues/16#issuecomment-221578416
> > 
> > 
> > ## 
> > 
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/BetaAndBit/GraTerenowa/issues/16#issuecomment-221625730
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/16#issuecomment-221629982

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
@pbiecek poprawilem mape, wykorzystuje inna biblioteke i prezentuje tylko Panstwa Europejskie. 
Ponizej print screeny tego jak mapa bedzie prezentowac sie na komorce

Dorzucilem tez kod QR. Jezeli wszystko jest OK, to mozesz dorzucic do aplikacji i zamknac zadanie

![pokoj_xo2_ver2_szeroko](https://cloud.githubusercontent.com/assets/6773454/15805658/3573458c-2b31-11e6-8b66-8967f58affe1.png)

**Comment by MarcinKosinski** [comment]
![pokoj_xo2_ver2_wasko](https://cloud.githubusercontent.com/assets/6773454/15805710/894b2a20-2b32-11e6-9134-95f4b4b1905d.png)

[nie wiem czy w mailach widac zalaczniku, ktore tu wrzucam]

**Comment by pbiecek** [comment]
Pomysł fajny,
dokładność tych liczb podejrzana (Warszawa 1 634 441)
obawiam się jedynie operacji na 6 cyfrowych liczbach.
Może wystarczy wynik podać z dokładnością do tysięcy?

Prawdopodobnie będę potrzebował od Ciebie odpowiedzi na pytania by
sprawdzić czy moje wyniki zgadzają się z Twoimi.

2016-06-05 15:32 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #16 https://github.com/BetaAndBit/GraTerenowa/issues/16 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/16#event-682159258, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvg2_Y7pB0hFaUCJ4ZHByXfxPmSvCks5qIs_6gaJpZM4Il3iu
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Zaokraglilem dane do tysiecy, zeby latwiej sie odejmowalo i dodawalo.
Odpowiedzi potem przesle mailem do wszystkich zadan

**Comment by MarcinKosinski** [comment]
w mini1001 - Dziekanat wprowadzilem ostatnie poprawki lingwistyczne. Mozna zaktualizowac zagadke na serwerze.
