### ISSUE TITLE
Pokój X05 - chord diagram

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#19]
Motywacja
- http://bl.ocks.org/mbostock/1046712
- http://www.delimited.io/blog/2013/12/8/chord-diagrams-in-d3
- http://www.visualcinnamon.com/2015/08/stretched-chord.html

Pakiet: https://github.com/mattflor/chorddiag/blob/master/vignettes/chorddiagram-vignette.Rmd

![pokoj_x05](https://cloud.githubusercontent.com/assets/6773454/15539022/31f8326e-2280-11e6-9399-dbc9f6e7d46a.png)

@pbiecek

**Comment by MarcinKosinski** [comment]
@prostkop myślisz, że jest jeszcze jakiś ciekawy zbiór z analizy przeżycia, który można łatwo zwizualizować w aplikacji dla dzieci w zadaniach tego pokroju jak to?

**Comment by MarcinKosinski** [comment]
Link na wszelki słuczaj https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1004.html

**Comment by pbiecek** [comment]
Zbiór danych świetny (tj Titanic), można wykorzystać pewnie w więcej niż
jednym zbiorze danych.
Może też zrobić z zadanie z mosaic plota i pytać o warukowe częstości (w
której klasie/płci/wieku przeżyło 50% osób)

Ten obrazek u mnie zajmuje 2.5 x szerokość ekranu telefonu.
Czy da się go jakośc zmieścić by był cały widoczny?

2016-05-25 15:38 GMT+02:00 Marcin Kosiński notifications@github.com:

> Link na wszelki słuczaj
> https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1004.html
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/19#issuecomment-221578609

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Można w opcjach knitra da się ustawiać szerokości output'u. Albo może dodać jakiegoś cssa, który będzie zwężał całego htmla do szerokości ekranu - to by automatycznie załatwiło sprawę na różnych wielkościach iUrządzeń?

**Comment by pbiecek** [comment]
To już nie opcje knitra (ten zarządza całym dokumentem) ale htmlwidget.

To on generuje tagi div i svg które mają teraz zahardkodowaną szerokość
672px.

Dla wykresów z rCharts da sie parametryzować szerokość wykresu w samym R,
jeżeli nie to pozostaje ręczna edycja htmla

W dniu 25 maja 2016 19:03 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Można w opcjach knitra da się ustawiać szerokości output'u. Albo może
> dodać jakiegoś cssa, który będzie zwężał całego htmla do szerokości ekranu
> - to by automatycznie załatwiło sprawę na różnych wielkościach iUrządzeń?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/19#issuecomment-221637915

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Faktycznie https://github.com/BetaAndBit/GraTerenowa/blob/master/MiNI/mini1004.html#L129

To pogrzebię w htmlwidgets'ach i poszukam ewentulanie moze cssa ktory wplywa na globalna szerokosc i wysokosc `div`ów i dostosowuje je do ekranu / user agenta

**Comment by pbiecek** [comment]
css chyba nie pomoże,
w svg renderowane są elementy wykresu (linie, koła itp) i te już mają na
sztywno ustawione położenie,
nie jestem pewien czy css może przeskalować położenie, imho nie.
lepiej chyba założyć najmniejszą możliwą rozdzielczość 320px (iphone 5) a
jak ekran ma większa to wokół już mogą być puste marginesy

ewentualnie można liczyć, że ktoś będzie przeglądał stronę w poziomym
układzie telefonu

W dniu 25 maja 2016 19:26 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Faktycznie
> https://github.com/BetaAndBit/GraTerenowa/blob/master/MiNI/mini1004.html#L129
> 
> To pogrzebię w htmlwidgets'ach i poszukam ewentulanie moze cssa ktory
> wplywa na globalna szerokosc i wysokosc divów i dostosowuje je do ekranu
> / user agenta
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/19#issuecomment-221644795

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by prostkop** [comment]
W zadaniu o Titanicu jest jeden błąd mocno dający po oczach, tam powinno być: "w danej klasie podrÓżujących".

**Comment by MarcinKosinski** [comment]
Dzięki @prostkop - już poprawiłem. Wstyd :P

2016-05-26 13:31 GMT+02:00 Piotr notifications@github.com:

**Comment by MarcinKosinski** [comment]
W htmlwidgetsach da się zmieniać szerokość i wysokość diva w którym
osadzony jest widget.
Jak tutaj

``` R
scale <- 0.9
chorddiag(titanic.mat, type = "bipartite",
          groupColors = groupColors, groupnameFontsize =15,
                    groupnamePadding = 25,
                    width = 672*scale, height = 480*scale,
```

jednak ostatecznie ręcznie w htmlu ustawiłem szerokość na
https://github.com/BetaAndBit/GraTerenowa/blob/master/MiNI/mini1004.html#L129

`style="width:100%;min-height:320px"`

i teraz bardzo schludnie wygląda to na telefonie.

Poprawiłem też dane, żeby opisy były polskie. Zmieniłem też wielkość
czcionek i marginesów tak by się lepiej komponował wykres.

@pbiecek jeżeli taki wykres jest OK, to czy możemy zaakceptować tę zagadkę?

W dniu 29 maja 2016 17:33 użytkownik Marcin Kosiński <m.p.kosinski@gmail.com

**Comment by MarcinKosinski** [comment]
![img_6618](https://cloud.githubusercontent.com/assets/6773454/15653819/a55b125e-268f-11e6-89b7-d42b0fca8f8e.PNG)

![img_6617](https://cloud.githubusercontent.com/assets/6773454/15653820/a9482d52-268f-11e6-8672-568478a5dd7c.PNG)

**Comment by MarcinKosinski** [comment]
![img_6616](https://cloud.githubusercontent.com/assets/6773454/15653822/b030e654-268f-11e6-94b0-71153ba6c806.PNG)

**Comment by pbiecek** [comment]
Moim zdaniem jest ok.
Dopisz tylko w treści coś na kształt 'Jako rozwiązanie należy podać procent
osób które utonęły w klasie o największej śmiertelności'. Tak by było
wiadomo co wpisać jako wynik.
Dodaj też kod QR i wrzucam do apki.

2016-05-30 18:20 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #19 https://github.com/BetaAndBit/GraTerenowa/issues/19 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/19#event-676198542, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvmy-pUr8AQtzf39MGpkrDIVBv7t6ks5qGw5QgaJpZM4ImdLK
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
A kod QR ostatecznie do jakich adresów internetowych podawać? Do raw.git czy do jakichś w innym miejscu? 

Marcin Kosinski

Dnia 01.06.2016 o godz. 22:31 Przemysław Biecek notifications@github.com napisał(a):

**Comment by pbiecek** [comment]
Najlepiej zgodnie z opisem ze strony:
https://github.com/BetaAndBit/GraTerenowa/wiki/Jak-dodawa%C4%87-zadania

czyli tekst w QR to BetaBit 1:XXXX:app/mini/miniXXXX.html gdzie XXXX to
czterocyfrowy kod zadania

Aplikacja tłumaczy te kody na adres
http://betabit.wiki/app/pl/locations/1/tasks/6911/
a na serwer betabit.wiki ręcznie przegrywam pliki z GitHuba

2016-06-02 0:03 GMT+02:00 Marcin Kosiński notifications@github.com:

> A kod QR ostatecznie do jakich adresów internetowych podawać? Do raw.git
> czy do jakichś w innym miejscu?
> 
> Marcin Kosinski
> 
> Dnia 01.06.2016 o godz. 22:31 Przemysław Biecek notifications@github.com
> napisał(a):
> 
> > Moim zdaniem jest ok.
> > Dopisz tylko w treści coś na kształt 'Jako rozwiązanie należy podać
> > procent
> > osób które utonęły w klasie o największej śmiertelności'. Tak by było
> > wiadomo co wpisać jako wynik.
> > Dodaj też kod QR i wrzucam do apki.
> > 
> > 2016-05-30 18:20 GMT+02:00 Marcin Kosiński notifications@github.com:
> > 
> > > Assigned #19 https://github.com/BetaAndBit/GraTerenowa/issues/19 to
> > > @pbiecek https://github.com/pbiecek.
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/BetaAndBit/GraTerenowa/issues/19#event-676198542,
> > > or mute
> > > the thread
> > > <
> > > https://github.com/notifications/unsubscribe/AEaPvmy-pUr8AQtzf39MGpkrDIVBv7t6ks5qGw5QgaJpZM4ImdLK
> > > 
> > > .
> > 
> > ## 
> > 
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/19#issuecomment-223138840,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvoQrKFVlzguahc9vKhB_MogRARcAks5qHgGxgaJpZM4ImdLK
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Ok dzięki

W dniu 2 czerwca 2016 00:20 użytkownik Przemysław Biecek <
notifications@github.com> napisał:

**Comment by MarcinKosinski** [comment]
Wprowadzilem poprawki. Przechodze do generowania kodu QR

**Comment by MarcinKosinski** [comment]
@pbiecek nie wiem czy juz zgrywales ten wykres na serwer, ale jeszcze poprawilem szerokosc

**Comment by MarcinKosinski** [comment]
w mini1004 - Pokoj A wprowadzilem ostatnie poprawki lingwistyczne. Mozna zaktualizowac zagadke na serwerze.
