### ISSUE TITLE
pakiet animation - zawieszony

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#2]
Moze wykorzystac animacje robione w R do stworzenia gry?
http://vis.supstat.com/categories.html#animation-ref

**Comment by pbiecek** [comment]
Fajny pomysł

2016-04-13 20:47 GMT+02:00 Marcin Kosiński notifications@github.com:

> Moze wykorzystac animacje robione w R do stworzenia gry?
> http://vis.supstat.com/categories.html#animation-ref
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/2

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Strona z galerią przykładów przestała działać więc póki co zawieszam wykorzystanie tego pakietu.
