### ISSUE TITLE
Pokój X06 - samochody i mapa ciepła

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#20]
@pbiecek  nie wiem czy to jest dobry zbiór danych (kolejny zbiór po angielsku). Myślisz, że `PogromcyDanych::auta2012` lepiej się sprawdzą na tym wykresie? Czy lepiej opisywać ten wykres? Czy potrzebne są gałęzie drzew klasteryzujących na brzegach?

![pokoj_x06](https://cloud.githubusercontent.com/assets/6773454/15541672/dc67a74a-228d-11e6-813e-d86bce90cfe6.png)

**Comment by MarcinKosinski** [comment]
Link https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1005.html

**Comment by pbiecek** [comment]
Zbiór danych jest fajny, ale nazwy kolumn był przetłumaczył na j. polski.

Może skrócić to zadanie i ograniczyć tylko do jednej zmiennej np samej
wagi? no nie wiem
coś trzeba zrobić by wykres mieścił się na telefonie, teraz to jakieś 3
szerokości ekranu.

Dendrogramy w kolumnach chyba nie mają sensu,
ale w wierszach mogłyby mieć.
Zostawiłbym je tylko jeżeli treść  zadania dotyczy dendrogramu (można np
zapytać o auto najbardziej podobne do X

Wykres można zrobić węższym np. nie pokazując wszystkich kolumna le tylko
ich część.

Też te wykresy powinny mieć parametr - szerokość

2016-05-25 15:38 GMT+02:00 Marcin Kosiński notifications@github.com:

> Link https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1005.html
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/20#issuecomment-221578708

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Aplikacja ma teraz ustawiona szerokosz na 100% dostepnego ekranu.

Wykres jest troche przydlugi, ale spelnia swoja role. Po kliknieciu w kafel/komorke wyswietla sie wartosc z podpisem kolumny i wiersza.

Przesylam zdjecia.

![img_6623](https://cloud.githubusercontent.com/assets/6773454/15654248/dea1a304-2692-11e6-9ae6-feac5d2a6fd8.PNG)

**Comment by MarcinKosinski** [comment]
![img_6619](https://cloud.githubusercontent.com/assets/6773454/15654255/e6cb50f2-2692-11e6-84ca-524076f3298f.PNG)

**Comment by MarcinKosinski** [comment]
@pbiecek jezeli wykres jest za wysoki, to mozna usunac kilka wierszy, np te ktore maja najdluzsze nazwy, zeby ostatecznie wykres byl szerszy.

Przekazuje zadania na Ciebie, zebys okreslij czy sie nadaje dana zagadka i czy jej nie skrocic. Potem mozesz odbic zadanie na mnie, jezeli mialbym wprowadzic eewntualne poprawki

**Comment by pbiecek** [comment]
Wykres mi się podoba, ale treść wydaje mi się zbyt złożona.
Może ją uprościć tak by trzeba było podać nazwy modeli auto najlżejsze i np
o największej mocy silnika?
W danych bym zmienił nazwy kolumn ana polskie i jednostki też na polskie
(funty na kg).

2016-05-30 18:19 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #20 https://github.com/BetaAndBit/GraTerenowa/issues/20 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/20#event-676198097, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvm8S4NyxQ_9pe5077kuHFW7afuUGks5qGw4pgaJpZM4Imijx
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Ok, poprawię w takim wypadku

W dniu 31 maja 2016 20:34 użytkownik Przemysław Biecek <
notifications@github.com> napisał:

**Comment by MarcinKosinski** [comment]
Dodalem polskie nazwy kolumn, niektore kolumny usunalem (zostalo chyba 7). Uproscilem tresc zadania wedlug zalecen :)

Wstawiam print-screen obecnego stanu. Przechodze do generowania kodu QR

![kompromis2](https://cloud.githubusercontent.com/assets/6773454/15752702/98b6cf86-28ef-11e6-964f-25be8819b032.png)

**Comment by pbiecek** [comment]
Super

W dniu 2 czerwca 2016 18:27 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Dodalem polskie nazwy kolumn, niektore kolumny usunalem (zostalo chyba 7).
> Uproscilem tresc zadania wedlug zalecen :)
> 
> Wstawiam print-screen obecnego stanu. Przechodze do generowania kodu QR
> 
> [image: kompromis2]
> https://cloud.githubusercontent.com/assets/6773454/15752702/98b6cf86-28ef-11e6-964f-25be8819b032.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/20#issuecomment-223345698,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvqjMw01J8puXD_kyhLBruMfQUmzbks5qHwRYgaJpZM4Imijx
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
@pbiecek  poprawilem tutaj jeszcze dane i tresc pytania. prosze zaktualizuj wersje na serwerze

**Comment by MarcinKosinski** [comment]
mini1005

**Comment by pbiecek** [comment]
zrobione

2016-06-06 16:40 GMT+02:00 Marcin Kosiński notifications@github.com:

> mini1005
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/20#issuecomment-223979323,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvt0sTaMJZHzBUvVm8GvuJaNlWzFCks5qJDF2gaJpZM4Imijx
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
w mini1005 - Pokoj B dodalem wskazowke. Mozna zaktualizowac zagadke na serwerze.
