### ISSUE TITLE
Pokój 537

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#22]
Nie widziałem issue dla tego pokoju.

Może warto odznaczyć jednego pracownika na wykresie w default'cie?
Pokazałem te aplikacje 3 osobom i nie domyslily sie, ze mozna odklikac osoby.
Moze odznaczenie jednego pracownika daloby do myslenia?

**Comment by MarcinKosinski** [comment]
@pbiecek

**Comment by pbiecek** [comment]
Dobry pomysł, zobaczę jak to zrobić

2016-05-30 17:16 GMT+02:00 Marcin Kosiński notifications@github.com:

> @pbiecek https://github.com/pbiecek
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/22#issuecomment-222512860,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvuJu8NfOimE86z5wVWhjQzfI8vREks5qGv80gaJpZM4Ip4C6
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Swoją drogą po przekręceniu telefonu wykres się nie poszerza. Może lepiej dać szerokość wykresu w procentach?

**Comment by pbiecek** [comment]
U mnie jak się obróci telefon to można powiększyć całą stronę i wtedy też
wykres jest większy.
Czy to wystarczy?

2016-05-30 20:10 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #22 https://github.com/BetaAndBit/GraTerenowa/issues/22 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/22#event-676258676, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvojL5oVREKvJDxrRCww6jJmsfOccks5qGygDgaJpZM4Ip4C6
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
U mnie nie (iPhone 5). Według mnie trzeba ustawić szerokość wykresu w procentach (100%) w div-ie zawierającym wykres 

Marcin Kosinski

Dnia 01.06.2016 o godz. 22:24 Przemysław Biecek notifications@github.com napisał(a):
