### ISSUE TITLE
Pokój X07 - wykres radarowy

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#23]
@pbiecek mam kolejna propozycję z wykresem radarowym. Nie pamiętam czy taki już mamy? Czy treść zadania nie ma zbyt skomplikowanego polecenia jeżeli chodzi o postać odpowiedzi?

![pokoj_x07](https://cloud.githubusercontent.com/assets/6773454/15654739/fd660ee8-2696-11e6-8e8e-e74028d7a9c5.png)

**Comment by MarcinKosinski** [comment]
https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1006.html

**Comment by pbiecek** [comment]
Mnie się podoba,
można odczytać wynik z wykresu nie trzeba dzielić dużych liczb.

Jedyne co bym zmienił to powiększył wartości tak by były dalej od środka
wykresu a bliżej brzegu. Będzie łatwiej je kliknąć/odczytać.

2016-05-30 18:48 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #23 https://github.com/BetaAndBit/GraTerenowa/issues/23 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/23#event-676215394, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvmZQD9gPTHSXnwfy04aywq2Dx9AMks5qGxTsgaJpZM4Ip7Z_
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Tez miałem przeczucie ze po pomniejszeniu do rozmiarów wyświetlacza niedobrze wyglądają wartości zbyt blisko środka 

Marcin Kosinski

Dnia 01.06.2016 o godz. 22:28 Przemysław Biecek notifications@github.com napisał(a):

**Comment by MarcinKosinski** [comment]
Nie dało się, tak prosto jakby się chciało, zmienić zakresu osi, więc osiągnąłem kompromis ustawiając osie jak w poniższym print screenie.

![kompromis](https://cloud.githubusercontent.com/assets/6773454/15752180/2a56ed3e-28ed-11e6-9046-43df75bd4c8a.png)

Dodaję kod QR

**Comment by pbiecek** [comment]
Super

W dniu 2 czerwca 2016 18:09 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Nie dało się, tak prosto jakby się chciało, zmienić zakresu osi, więc
> osiągnąłem kompromis ustawiając osie jak w poniższym print screenie.
> 
> [image: kompromis]
> https://cloud.githubusercontent.com/assets/6773454/15752180/2a56ed3e-28ed-11e6-9046-43df75bd4c8a.png
> 
> Dodaję kod QR
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/23#issuecomment-223340682,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPviR4f7I_oN0WmqodlGuu0jCe1aYWks5qHwBLgaJpZM4Ip7Z_
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Dorzucilem jedna poprawke do danych w mini1006 bo nie dalo sie podac jednoznacznej odpowiedzi. Trzeba bedzie zaktualizowac wersje na serwerze :)

**Comment by pbiecek** [comment]
zrobione

W dniu 6 czerwca 2016 16:46 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Dorzucilem jedna poprawke do danych w mini1006 bo nie dalo sie podac
> jednoznacznej odpowiedzi. Trzeba bedzie zaktualizowac wersje na serwerze :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/23#issuecomment-223980993,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvqnuqldJDbaqKCIqDDTRv30_h2iOks5qJDK7gaJpZM4Ip7Z_
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
w mini1006 - Pokoj C poprawilem tresc. Mozna zaktualizowac zagadke na serwerze.
