### ISSUE TITLE
Pokój X08 - pogoda w Tokyo

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#24]
@pbiecek wykorzystuję highcharter'a do maksimum :)

Kolejna propozycja w zalaczniku

![pokoj_x08_1](https://cloud.githubusercontent.com/assets/6773454/15655905/13654848-26a2-11e6-8689-03ca4de77cb7.png)

![pokoj_x08_2](https://cloud.githubusercontent.com/assets/6773454/15655906/162f1356-26a2-11e6-9e7d-f124af397f0f.png)

**Comment by MarcinKosinski** [comment]
https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1007.html

**Comment by pbiecek** [comment]
Wykres jest fajny i treść też, ale można rozszerzyć opis by ułatwić
odgadnięcie co powinno być wynikiem.

Na początku są trzy pytania ale nie wiadomo czy trzeba odpowiedzieć na
każde czy to jest jedno pytanie powtórzone.

Zastanawiam się tez nad tym podawaniem wyników z dokładnością do dwóch cyfr
dziesiętnych, może zmniejszyć tę dokładność?
Nie jest tez jasne czy dzielić celciusze na milimetry czy jakoś zmienić
jednostki?

2016-05-30 20:08 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #24 https://github.com/BetaAndBit/GraTerenowa/issues/24 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/24#event-676257982, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvqk6lR4g-3d2bwO0UqscWsQZILSyks5qGyeogaJpZM4Ip9jP
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Poprawiłem treść

> Odpowiedz na następujące pytania dotyczące pogody w Tokyo. W jakim miesiącu stosunek stopni Celsjusza do opadów w mm był najmniejszy? Jaka jest wartość największego bezjednostkowego stosunku stopni Celsjusza do opadów w mm w zaprezentowanym wykresie? Jaki procent w ciągu przedstawionego półrocza stanowią godziny słoneczne? Odpowiedź podaj w formacie `miesiąc,wartość,procent`, gdzie wartość podaj w zaokrągleniu do 2 miejsca po przecinku a przy procentach podaj samą liczbę bez znaku `%`.

Czyli chodzi o bezjednostkowy **stosunek** wartości. Trzeba odpowiedzieć na 3 pytania.

A co do dokładności, to chodzi o zmianę, że dokładność do 1 miejsca po przecinku :)?

Jeżeli teraz jest OK, to mogę przygotować kod QR.

**Comment by pbiecek** [comment]
Ok, sprawdźmy to zadanie w boju.
Osobiście mam uraz do zadań, które wymagają dzielenia z dokładnością do
miejsc po przecinku, ale to dlatego że nie potrafię takich rzeczy robić w
pamięci.
Ale może młodzież jest bystrzejsza, przetestujemy w boju.

2016-06-02 17:52 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #24 https://github.com/BetaAndBit/GraTerenowa/issues/24 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/24#event-680003519, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvlHmO72aohUKZd3kAnIpF77nb4Hpks5qHvw7gaJpZM4Ip9jP
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Moze sa sie wyjsc z aplikacji, włączyć kalkulator, podzielić i wejść z powrotem /:)? Tak to sobie wyobrażam 

Marcin Kosinski

Dnia 02.06.2016 o godz. 19:11 Przemysław Biecek notifications@github.com napisał(a):

**Comment by pbiecek** [comment]
Ok, tak zróbmy,
we wtorek rozwieszę kody na MIMUWie (na MINI juz są) i będziemy mogli
rozpocząć grę

W dniu 2 czerwca 2016 23:40 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Moze sa sie wyjsc z aplikacji, włączyć kalkulator, podzielić i wejść z
> powrotem /:)? Tak to sobie wyobrażam
> 
> Marcin Kosinski
> 
> Dnia 02.06.2016 o godz. 19:11 Przemysław Biecek notifications@github.com
> napisał(a):
> 
> > Ok, sprawdźmy to zadanie w boju.
> > Osobiście mam uraz do zadań, które wymagają dzielenia z dokładnością do
> > miejsc po przecinku, ale to dlatego że nie potrafię takich rzeczy robić w
> > pamięci.
> > Ale może młodzież jest bystrzejsza, przetestujemy w boju.
> > 
> > 2016-06-02 17:52 GMT+02:00 Marcin Kosiński notifications@github.com:
> > 
> > > Assigned #24 https://github.com/BetaAndBit/GraTerenowa/issues/24 to
> > > @pbiecek https://github.com/pbiecek.
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/BetaAndBit/GraTerenowa/issues/24#event-680003519,
> > > or mute
> > > the thread
> > > <
> > > https://github.com/notifications/unsubscribe/AEaPvlHmO72aohUKZd3kAnIpF77nb4Hpks5qHvw7gaJpZM4Ip9jP
> > > 
> > > .
> > 
> > ## 
> > 
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> > —
> > You are receiving this because you were assigned.
> > 
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/24#issuecomment-223431216,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvgYMaqZ8wKmNwvqvc8nT6FQoCW_wks5qH03dgaJpZM4Ip9jP
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
@pbiecek w 1007 tez zmienilem lekko tresc . czy moglbys zaktualizowac zadanie na serwerze?

**Comment by pbiecek** [comment]
zrobione

2016-06-06 16:51 GMT+02:00 Marcin Kosiński notifications@github.com:

> @pbiecek https://github.com/pbiecek w 1007 tez zmienilem lekko tresc .
> czy moglbys zaktualizowac zadanie na serwerze?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/24#issuecomment-223982618,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvtgeJVHSyIzcQ5GnW10oTFSHzRUpks5qJDPsgaJpZM4Ip9jP
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Jeżeli to miał być pokój D, to ja nie widzę tej poprawki

**Comment by MarcinKosinski** [comment]
W aplikacji.
Zas na githubie jest wersja https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1007.html
gdzie w ostatnim zdaniu z Zadania jest wpisane `gdzie wartosci PROCENT podaj w...` - to powinno byc w aplikacji tez

**Comment by pbiecek** [comment]
w aplikacji wyświetlają się strony o adresie
http://betabit.wiki/app/pl/locations/1/tasks/1007
(dla innych zadań trzeba zmienić ostatni człon
teraz po winno być ok

W dniu 6 czerwca 2016 21:05 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> W aplikacji.
> Zas na githubie jest wersja
> https://rawgit.com/BetaAndBit/GraTerenowa/master/MiNI/mini1007.html
> gdzie w ostatnim zdaniu z Zadania jest wpisane gdzie wartosci PROCENT
> podaj w... - to powinno byc w aplikacji tez
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/24#issuecomment-224056155,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvj-PHTmcP6g31WmpInL4_eCIrLvYks5qJG9vgaJpZM4Ip9jP
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
w mini1007 - Pokoj D poprawilem tresc. Mozna zaktualizowac zagadke na serwerze.

**Comment by pbiecek** [comment]
wszystkie treści zadań zostały zaktualizowane

2016-06-07 20:58 GMT+02:00 Marcin Kosiński notifications@github.com:

> w mini1007 - Pokoj D poprawilem tresc. Mozna zaktualizowac zagadke na
> serwerze.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/24#issuecomment-224380234,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvrJm_ddS7ujegve2wlLyHIkqAbhCks5qJb9hgaJpZM4Ip9jP
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek
