### ISSUE TITLE
Inspiration: GameOfThrones

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/GraTerenowa#25]
@MarcinKosinski 
nice vis, maybe it will be kind of inspiration
https://interactive.twitter.com/game-of-thrones/#?episode=13

**Comment by MarcinKosinski** [comment]
Nie ogladalem ani nie czytalem. Jestem odporny na chorobe Gry o Tron, tak samo jak na gorączkę Big-Date'y. Nie chce wyglupiac sie z tworzeniem tresci, pomimo, ze ten wykres nie wyglada na zbyt skomplikowany :).

Tutaj jedyne pytanie jakie mozna zadac, to ile potrzeba powiazan/znajomosci aby polaczyc jedna osobe z druga?

**Comment by pbiecek** [comment]
Ok, to zignoruj ten wykres.
chyba, że wolisz time-line dla StarWars / Władcy pierścieni w stylu XKCD

http://imgs.xkcd.com/comics/movie_narrative_charts_large.png
https://aruguladesigns.files.wordpress.com/2009/11/star_wars_diagram.png?w=700&h=341

LoTR będzie trudno zmieścić na telefonie, ale zabawa byłaby w stylu 'gdzie
jest wally'

2016-06-06 0:38 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #25 https://github.com/BetaAndBit/GraTerenowa/issues/25 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/25#event-682274381, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvo-fFKoj-R2qd3etXQCzAJ0-LcjTks5qI0_YgaJpZM4IuJ_Y
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
To się nie nadaje na telefon :P

W dniu 6 czerwca 2016 01:12 użytkownik Przemysław Biecek <
notifications@github.com> napisał:

**Comment by pbiecek** [comment]
zamykamy issue?

**Comment by MarcinKosinski** [comment]
Najwyżej we wrześniu
