### ISSUE TITLE
kody QR

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/GraTerenowa#26]
@MarcinKosinski 
Te kody QR nie są poprawne, ponieważ były generowanie jako URL i zamiast
BetaBit 1:XXXX:app/mini/miniXXXX.html
mają treść
http://BetaBit 1:XXXX:app/mini/miniXXXX.html

Aby wygenerować poprawny kod trzeba wejść na stronę 
http://www.qr-online.pl/index.php
przełączyć się na 'Dowolny tekst' i wybrać jakość M rozmiar 6.

**Comment by MarcinKosinski** [comment]
Czy mam to poprawić czy Ty juz to poprawiłeś? Wracam do projektu o 21;00

Marcin Kosinski

Dnia 05.06.2016 o godz. 16:41 Przemysław Biecek notifications@github.com napisał(a):

**Comment by pbiecek** [comment]
Popraw to proszę do swoich zadań.
Aktualnie walczę z dodawaniem nowych html'i z jakiegoś powodu te nowe htmle
zachowują się inaczej niż stare.

W dniu 5 czerwca 2016 20:19 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Czy mam to poprawić czy Ty juz to poprawiłeś? Wracam do projektu o 21;00
> 
> Marcin Kosinski
> 
> Dnia 05.06.2016 o godz. 16:41 Przemysław Biecek notifications@github.com
> napisał(a):
> 
> > @MarcinKosinski
> > Te kody QR nie są poprawne, ponieważ były generowanie jako URL i zamiast
> > BetaBit 1:XXXX:app/mini/miniXXXX.html
> > mają treść
> > http://BetaBit 1:XXXX:app/mini/miniXXXX.html
> > 
> > Aby wygenerować poprawny kod trzeba wejść na stronę
> > http://www.qr-online.pl/index.php
> > przełączyć się na 'Dowolny tekst' i wybrać jakość M rozmiar 6.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/26#issuecomment-223828397,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvj2AP2xhwIfGo_KHLUOGiINnHCVcks5qIxM7gaJpZM4IuXnr
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
poprawione dla 8 wykresowod 1000 do 1007

**Comment by pbiecek** [comment]
Super,
kody ze strony
https://github.com/BetaAndBit/GraTerenowa/blob/master/MiNI/README.md

już się skanuja apką

2016-06-05 22:47 GMT+02:00 Marcin Kosiński notifications@github.com:

> poprawione dla 8 wykresowod 1000 do 1007
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/26#issuecomment-223836643,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvje8eyw1bK1aja64mUge8N52cz8qks5qIzXQgaJpZM4IuXnr
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Działają Ci wszystkie kody?
Mi 19te i 20te zadanie się jeszcze nie skanuje, ale moze nie ma tych zadan
w aplikacji jeszcze.

2016-06-05 22:49 GMT+02:00 Przemysław Biecek notifications@github.com:

**Comment by pbiecek** [comment]
dodałem juz wszystkie kody na serwer,
powinno działać 20 zadań dla mimuw i 10 dla mini

W dniu 6 czerwca 2016 14:21 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Działają Ci wszystkie kody?
> Mi 19te i 20te zadanie się jeszcze nie skanuje, ale moze nie ma tych zadan
> w aplikacji jeszcze.
> 
> 2016-06-05 22:49 GMT+02:00 Przemysław Biecek notifications@github.com:
> 
> > Super,
> > kody ze strony
> > https://github.com/BetaAndBit/GraTerenowa/blob/master/MiNI/README.md
> > 
> > już się skanuja apką
> > 
> > 2016-06-05 22:47 GMT+02:00 Marcin Kosiński notifications@github.com:
> > 
> > > poprawione dla 8 wykresowod 1000 do 1007
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> > 
> > https://github.com/BetaAndBit/GraTerenowa/issues/26#issuecomment-223836643
> > 
> > > ,
> > > or mute the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AEaPvje8eyw1bK1aja64mUge8N52cz8qks5qIzXQgaJpZM4IuXnr
> > 
> > > .
> > 
> > ## 
> > 
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > <
> > https://github.com/BetaAndBit/GraTerenowa/issues/26#issuecomment-223836736
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AGdazuUUzueoF0pW_JOqGTFfdb6Zdykeks5qIzY9gaJpZM4IuXnr
> > 
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/26#issuecomment-223943221,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvg63Kdsd-dzYBG1SFN2hG6eyJ6UKks5qJBDSgaJpZM4IuXnr
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek
