### ISSUE TITLE
Pokój X09 - streamgraph z IMDB

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#27]
Czy [nie zawsze sensowny wykres strumieniowy](http://www.visualisingdata.com/2010/08/making-sense-of-streamgraphs/) pomoże odczytać potrzebne informacje?

@pbiecek propozycja kolejnego wykresu. Link, któru umieściłem w opisie wykresu przenosi to ciekawego wpisu, który jest oceanem nowych form wizualizacji.

Propozycje tego pokoju w załączniku

![streamgraph_szeroko](https://cloud.githubusercontent.com/assets/6773454/15808421/8939ecac-2b77-11e6-9d5d-cdbc8ef0645e.png)

![streamgraph_wasko](https://cloud.githubusercontent.com/assets/6773454/15808423/8d2ce670-2b77-11e6-8950-e2a50b94949a.png)

**Comment by pbiecek** [comment]
Jest ok, tylko przy liczbach w prawym górnym rogu warto napisać że to z przedziału 1900-2010,
inaczej ktoś może założyć, że dotyczą one 1980-2000 (chyba że dotyczą)

**Comment by MarcinKosinski** [comment]
Nie rozumiem tego

> przy liczbach w prawym górnym rogu warto napisać że to z przedziału 1900-2010

gdzie to dopisać?

Oś OX ma legendę z której jasno wynika jaki jest zakres, a pytanie jest o fragment danych tylko :>

**Comment by pbiecek** [comment]
Ok, dopiero teraz zauważyłem że te liczby są na rok a nie przedstawiają
całego pola.
Może da się w opisie napisać 'Dramat w 1990: 555', teraz trudno odgadnąć
dokładnie jakiego okresu dotyczą te liczby.

Cały wykres jest wycentrowany wokół 1400 (na osi OY), może lepiej tę oś OY
usunąć? lub wycentrować wokół 0?

W dniu 6 czerwca 2016 11:19 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Nie rozumiem tego
> 
> przy liczbach w prawym górnym rogu warto napisać że to z przedziału
> 1900-2010
> 
> gdzie to dopisać?
> 
> Oś OX ma legendę z której jasno wynika jaki jest zakres, a pytanie jest o
> fragment danych tylko :>
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/27#issuecomment-223908243,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvj00UmmCCZ74PUiFLLBpw8p699ELks5qI-Y2gaJpZM4IudKj
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
To jest właśnie kwestia stream-graphów :) w linku do bloga w tresci zadania
jest napisane po co stosuje sie taki zabieg, ze centruje sie os OY w srodku
zakresu danych i dlaczego taki zabieg nie jest dobrym zwyczajem.

Wiec to dobrze, ze od razu narzuca nam sie kilka uwag.

To tak jakby umiescic wykres kolowy, a potem dac link do wpisu w ktorym
ktos pokazuje, ze wykres kolowy nie jest tak znakomitym odkryciem jak samo
kolo :)

W dniu 6 czerwca 2016 11:25 użytkownik Przemysław Biecek <
notifications@github.com> napisał:

**Comment by pbiecek** [comment]
Ok,
to do mnie przemawia

W dniu 6 czerwca 2016 11:36 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> To jest właśnie kwestia stream-graphów :) w linku do bloga w tresci zadania
> jest napisane po co stosuje sie taki zabieg, ze centruje sie os OY w srodku
> zakresu danych i dlaczego taki zabieg nie jest dobrym zwyczajem.
> 
> Wiec to dobrze, ze od razu narzuca nam sie kilka uwag.
> 
> To tak jakby umiescic wykres kolowy, a potem dac link do wpisu w ktorym
> ktos pokazuje, ze wykres kolowy nie jest tak znakomitym odkryciem jak samo
> kolo :)
> 
> W dniu 6 czerwca 2016 11:25 użytkownik Przemysław Biecek <
> notifications@github.com> napisał:
> 
> > Ok, dopiero teraz zauważyłem że te liczby są na rok a nie przedstawiają
> > całego pola.
> > Może da się w opisie napisać 'Dramat w 1990: 555', teraz trudno odgadnąć
> > dokładnie jakiego okresu dotyczą te liczby.
> > 
> > Cały wykres jest wycentrowany wokół 1400 (na osi OY), może lepiej tę oś
> > OY
> > usunąć? lub wycentrować wokół 0?
> > 
> > W dniu 6 czerwca 2016 11:19 użytkownik Marcin Kosiński <
> > notifications@github.com> napisał:
> > 
> > > Nie rozumiem tego
> > > 
> > > przy liczbach w prawym górnym rogu warto napisać że to z przedziału
> > > 1900-2010
> > > 
> > > gdzie to dopisać?
> > > 
> > > Oś OX ma legendę z której jasno wynika jaki jest zakres, a pytanie
> > > jest o
> > > fragment danych tylko :>
> > > 
> > > —
> > > You are receiving this because you were assigned.
> > > Reply to this email directly, view it on GitHub
> > > <
> > 
> > https://github.com/BetaAndBit/GraTerenowa/issues/27#issuecomment-223908243
> > 
> > > ,
> > > or mute the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AEaPvj00UmmCCZ74PUiFLLBpw8p699ELks5qI-Y2gaJpZM4IudKj
> > 
> > > .
> > 
> > ## 
> > 
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> > https://github.com/BetaAndBit/GraTerenowa/issues/27#issuecomment-223909486
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AGdazrL7gDlnXbsTZ_sMiyz8mMop9IOgks5qI-eMgaJpZM4IudKj
> > 
> > .
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/27#issuecomment-223911798,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvvRf4JveN27P8iIm-rt8d0cVJH-Sks5qI-oRgaJpZM4IudKj
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Tutaj jest winietka pakietu i faktycznie wykres zaczynajacy sie w 0 do mnie najbardziej przemawia http://hrbrmstr.github.io/streamgraph/

To zamykam w takim wypadku :)

**Comment by MarcinKosinski** [comment]
Jeszcze jedno typo znalazlem w mini1008 - pokoj E

**Comment by MarcinKosinski** [comment]
w mini1008 - Pokoj E wprowadzilem ostatnie poprawki lingwistyczne. Mozna zaktualizowac zagadke na serwerze.
