### ISSUE TITLE
Pokoj X10 - infografika z diagramem Venna

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#28]
@pbiecek trafiłem jeszcze na fajną infografikę z diagramem Venna

To mamy teraz 10 zadań na MiNI i 10 na MIMUWie :)

**Comment by MarcinKosinski** [comment]
![venn_wasko](https://cloud.githubusercontent.com/assets/6773454/15808685/972d01da-2b7e-11e6-8299-6434525d8fa2.png)

**Comment by pbiecek** [comment]
Super wykres.
Jeżeli go dobrze czytam to w cappuccino powinna być czekolada.
Nie jestem pewien czy da się z niego odczytać proporcje (tj. ja nie
potrafię).

Usuń proszę ostatnią połowę zdania (po ,,tak by móc pomagać mamie...'') by
nie drażnić feministek.

2016-06-06 0:35 GMT+02:00 Marcin Kosiński notifications@github.com:

> Assigned #28 https://github.com/BetaAndBit/GraTerenowa/issues/28 to
> @pbiecek https://github.com/pbiecek.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/28#event-682273867, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvvwzmh39X3NOiTEC5WFZAgLcXyL4ks5qI09HgaJpZM4Iudqh
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Proporcje trudno, ale widać, które półkola/części pól są większe od innych :)

Zmienię mamę na `rodziców` :) albo po prostu usunę

**Comment by MarcinKosinski** [comment]
Zamieniłem na rodziców.

**Comment by pbiecek** [comment]
A czy nie jest tak, że latte to tylko przecięcie trzech kół,
i pole przecięcia jest takie samo dla każdego ze składników,
więc nie można odczytać którego jest więcej?

W dniu 6 czerwca 2016 11:14 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Proporcje trudno, ale widać, które półkola/części pól są większe od innych
> :)
> 
> Zmienię mamę na rodziców :) albo po prostu usunę
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/28#issuecomment-223907122,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvhRH-iAliV8Rwr5G2k63Q2spH1CGks5qI-UCgaJpZM4Iudqh
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Coffea, Foam, Milk jest chyba faktycznie tyle samo, a najmniej Chocolate.
Musialem pozno robic ten wykres :)

To moze zadac pytanie: `wpisz 3 najwazniejsze skladniki`?

**Comment by pbiecek** [comment]
IMHO z tego wykresu wynika, że w latte nie ma czekolady (jest za to w cap.)

2016-06-06 11:33 GMT+02:00 Marcin Kosiński notifications@github.com:

> Coffea, Foam, Milk jest chyba faktycznie tyle samo, a najmniej Chocolate.
> Musialem pozno robic ten wykres :)
> 
> To moze zadac pytanie: wpisz 3 najwazniejsze skladniki?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/28#issuecomment-223911351,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvhnhZp9xJjWM4v8Anuqp14YVhuBDks5qI-mEgaJpZM4Iudqh
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Skoro to trudniejsze niz myslalem, to tym lepiej dla zadania. Zmienilem tresc na `wymien 3 skladniki kawy latte` :)
