### ISSUE TITLE
Lista lokacji - aplikacja

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#29]
@pbiecek  poki co u mnie w aplikacji jest pusta. Nie ma ani MiNI ani MIMUW.

**Comment by pbiecek** [comment]
A czy jesteś zalogowany?
Czy pusta oznacza że wszystkie są zakryte czy też że żadne się nie
wyświetlają?
Ja mam 10 na MINI i 17 na MIMUW

2016-06-06 11:37 GMT+02:00 Marcin Kosiński notifications@github.com:

> @pbiecek https://github.com/pbiecek poki co u mnie w aplikacji jest
> pusta. Nie ma ani MiNI ani MIMUW.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/29, or mute the thread
> https://github.com/notifications/unsubscribe/AEaPvhEO1paNVARruJcwN8ZEwkE4kkakks5qI-pdgaJpZM4IuuJY
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Tak. Przesyłam Ci na maila print screeny z aplikacji

W dniu 6 czerwca 2016 11:39 użytkownik Przemysław Biecek <
notifications@github.com> napisał:

**Comment by MarcinKosinski** [comment]
Po wylogowaniu I zalogowaniu ponownym pojawiła sie lista. Widze juz 18 na mimuwie i 10 na mini 

Marcin Kosinski

Dnia 06.06.2016 o godz. 11:39 Przemysław Biecek notifications@github.com napisał(a):

**Comment by pbiecek** [comment]
juz powinno byc 20

2016-06-06 16:22 GMT+02:00 Marcin Kosiński notifications@github.com:

> Closed #29 https://github.com/BetaAndBit/GraTerenowa/issues/29.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/29#event-682919125, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEaPvrJONsA-9AxA7YLt0cIfCbRcoToEks5qJC0jgaJpZM4IuuJY
> .

## 

pozdrawiam serdecznie,
Przemysław Biecek
