### ISSUE TITLE
Pokój X00 - wciaz szukam biblioteki do niego

### ISSUE THREAD

**Issue by MarcinKosinski** [BetaAndBit/GraTerenowa#3]
Kiedys widzialem takie wykresy robiona w R, nie pamietam czy bylo to przy okazji #2  czy jednak jakis htmlwidget, ale pamietam, ze zaznaczalo sie wartosc na osi OY i rozpoczynalo to bieg w kierunku wykresu takich strzalek i kiedy napotkaly one wykres to uciekaly na dol na os OX tak ze wskazywaly argument na osi OX dla wartoscy z osi OY.

Pomyslalem o takich dwoch wykresach o wspolnej osi OX

![przyklad123](https://cloud.githubusercontent.com/assets/6773454/14505496/b5ffb6d2-01b9-11e6-9af6-4ec6810a64e7.JPG)

Fabula polegac moglaby na czyms takim

Beta i Bit zostali poproszeni o zrobienie zakupów do wydziałowego bufetu. 
Kucharz, z zamiłowania matematyk, uwielbiając funkcję logarytmiczną podał zamówienie w wartościach logarytmu. 

Było to
- log( # pomidory ) = 43
- log( # jajka ) = 85
- log( # bułek ) = 106

Sklepikarz od dłuższego czasu zgłebiał tajemnice funkcji `sklomplikowana funkcja` i przyjmował zamówienia tylko w wartościach tej funkcji. 
Pomóż odgadnąć Becie i Bitowi wartości funkcji `skomplikowana funkcja`, znając wartości funkcji logarytmicznej

**Comment by pbiecek** [comment]
Fajne,
ponoć odczytywanie wartości funkcji to dla wielu uczniów duża trudność,
więc złożenie dwóch funkcji to już wyzwanie

W dniu 13 kwietnia 2016 20:58 użytkownik Marcin Kosiński <
notifications@github.com> napisał:

> Kiedys widzialem takie wykresy robiona w R, nie pamietam czy bylo to przy
> okazji #2 https://github.com/BetaAndBit/GraTerenowa/issues/2 czy jednak
> jakis htmlwidget, ale pamietam, ze zaznaczalo sie wartosc na osi OY i
> rozpoczynalo to bieg w kierunku wykresu takich strzalek i kiedy napotkaly
> one wykres to uciekaly na dol na os OX tak ze wskazywaly argument na osi OX
> dla wartoscy z osi OY.
> 
> Pomyslalem o takich dwoch wykresach o wspolnej osi OX
> 
> [image: przyklad123]
> https://cloud.githubusercontent.com/assets/6773454/14505496/b5ffb6d2-01b9-11e6-9af6-4ec6810a64e7.JPG
> 
> Fabula polegac moglaby na czyms takim
> 
> Beta i Bit zostali poproszeni o zrobienie zakupów do wydziałowego bufetu.
> Kucharz, z zamiłowania matematyk, uwielbiając funkcję logarytmiczną podał
> zamówienie w wartościach logarytmu.
> 
> Było to
> - log( # pomidory ) = 43
> - log( # jajka ) = 85
> - log( # bułek ) = 106
> 
> Sklepikarz od dłuższego czasu zgłebiał tajemnice funkcji sklomplikowana
> funkcja i przyjmował zamówienia tylko w wartościach tej funkcji.
> Pomóż odgadnąć Becie i Bitowi wartości funkcji skomplikowana funkcja,
> znając wartości funkcji logarytmicznej
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/3

## 

pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
przelozylbym to na pozniejsza edycje
