### ISSUE TITLE
pokój 222

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/GraTerenowa#4]
- W opisie w przedziale wiekowym mężczyzn jest literówka. Zamiast `25-24` powinno być `25-34`.
- To jest fajny i kolorowy wykres (na pewno zachęca), ale ciężko mi się liczyło tych ludzików na małym ekranie. Może na tablecie by to lepiej pasowało.
- Dobrym pomysłem jest wskazanie, że nazwa techniki to ISOTYPE. Co Ty na to, żeby pod tym napisem krył się widoczny link do wikipedi albo jakiegoś fajnego wpisu na blog na ten temat?
- Podobnie na wykresie w legendzie jest `BMI` - nie jest to nigdzie wyjaśnione, ale link do wikipedi czy wpisu na blog by tutaj pasował.
- Może warto umieścić informacje, z jakiego źródła pochodzą dane (o ile są prawdziwe)?
- Czy te kropki pomiędzy wykresem a tekstem są potrzebne? Nie działają Wam tagi `<br><br>`?
- Szedłbym w kierunku prezentowania wykresów przed tekstem, żeby ktoś po ciekawym wykresie był zmotywowany do czytania opisu zadania. A najlepiej wykres, pod którym by był przycisk do pokazania opisu.
- Zauważyłem, że niekiedy starasz się pisać `ciała / niedowagę / nadwagę`. Nawet w naszym artykule z RTCGA. Ja nie wiem jak to rozumieć: to jest wyliczenie czy to jest tekst do wybrania a reszta jest do skasowania? Może dobrze napisać w prosty sposób `ciała, niedowagę czy nadwagę`?
- Może pod spodem dać link: więcej podobnych badań można znaleźć tutaj: i link do bloga albo strony rządowej, która na podobnych danych prezentuje raporty?

**Comment by pbiecek** [comment]
Dzięki, poprawione.
Świetny pomysł z tymi linkami do dodatkowych materiałów. Dodałem.
Tekst przed wykresem skróciłem, komentarze przeniosłem pod wykres.

**Comment by MarcinKosinski** [comment]
Gdzieś są zmiany odnośnie tego pokoju? mini1313.Rmd sie nie zmienil, pomimo, ze mini1313.html sie zmienil

**Comment by pbiecek** [comment]
Początkowo każdy html był generowany z Rmd,
ale wynikowe pliki były duże (około 1MB z wszystkimi bibliotekami)
więc ostateczna wersja była robiona semiręcznie aby była mniejsza (teraz
kilka kB)

2016-05-24 19:55 GMT+02:00 Marcin Kosiński notifications@github.com:

> Gdzieś są zmiany odnośnie tego pokoju? mini1313.Rmd sie nie zmienil,
> pomimo, ze mini1313.html sie zmienil
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/BetaAndBit/GraTerenowa/issues/4#issuecomment-221347170

## 

pozdrawiam serdecznie,
Przemysław Biecek
